import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Nunito } from 'next/font/google'
import Navbar from './components/Navbar/Navbar'
import ClientOnly from './components/ClientOnly'
// import Modal from './components/Modals/Modal'
import RegisterModal from './components/Modals/RegisterModal'
import ToasterProvider from './Providers/ToasterProvider'
import LoginModal from './components/Modals/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/Modals/RentModal'

const inter = Inter({ subsets: ['latin'] })
const font = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: 'Airbnb | Holiday rentals and more!!',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          {/* <Modal actionLabel='Submit' title='Title Prop' isOpen  /> */}
          <RentModal />
          <LoginModal />
          <RegisterModal />
          <Navbar currentUser = {currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
